### PR TITLE
New Backup and Restore Documentation

### PR DESCRIPTION
**Pull request by fabiogomezdiaz**
### What this PR does / why we need it

This adds new documentation for backing up and restoring Jenkins installation on PVC.

### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Review by timja — APPROVED** [review]
lgtm not tested, will leave for a bit and see if other feedback

**Review by torstenwalter — COMMENTED** [review]
@fabiodcasilva could you look into the issues reported by CI?

```
/github/workspace/charts/jenkins/README.md:453:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
/github/workspace/charts/jenkins/README.md:549:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
/github/workspace/charts/jenkins/README.md:590:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
/github/workspace/charts/jenkins/README.md:591:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
/github/workspace/charts/jenkins/README.md:592:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
/github/workspace/charts/jenkins/README.md:593:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
/github/workspace/charts/jenkins/README.md:611:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
```

In the meantime there was also a PR merged to main branch so ideally you would merge main into you branch and bump the version once more.

Regarding your changes: I really like them. I think this is a good step forward in terms of documentation and it should help others to get started with backup and restore. I haven't tested it myself, but everything I read makes sense. 
@timja I am in favor of merging it once CI is happy.

**Review by oleg-nenashev — COMMENTED** [review]
The guide itself loos good. Regarding the unordered lists, unfortunately Markdown is not designed for lists with long bodies and examples. While it will render okay from user perspective, it will not be actually a list for machine representation. I suggest reformatting it

Maybe just such a format?

```
**Step 6.** Deploy the job using the following command 
```

Adding headers might work too

**Review by timja — APPROVED** [review]

**Comment by fabiogomezdiaz** [comment]
@oleg-nenashev @timja @torstenwalter, thanks a lot for your great feedback! 🙏

I reorganized the content to make it more machine-readable and hopefully pass all the lint tests.

I also pulled the latest changes from upstream into my fork and updated the Chart version in **README.md** and **Chart.yaml** accordingly.

This update should be ready, so please let me know if there is anything else I need to do to get this merged.

**Comment by torstenwalter** [comment]
@fabiodcasilva changes look good to me also ci checks pass now. The only thing left is to fix DCO check. See https://github.com/jenkinsci/helm-charts/pull/436/checks?check_run_id=3405606314 for explanation how to do that.

**Comment by fabiogomezdiaz** [comment]
@oleg-nenashev @timja @torstenwalter, I fixed the DCO check. Still getting used to that part BTW lol

**Review by timja — APPROVED** [review]

**Pull request merged**
