### PR TITLE
Add variables to support cert-manager generated certificates

### PR DESCRIPTION
**Pull request by benzch**
### What does this PR do?
When Issuing the SSL certificate with Cert-manager it creates Kubernetes secret of type kubernetes.io/tls without the ability to define the secret keys (jks file is stored in keystore.jks). Since the helm chart expects the keystore file in the hardcoded key name it is not possible to use cert-manager issued certificate.

This PR adds the ability to use a secret that already has SSL keystore with a variable name key in the secret and not just the default "jenkins-jks-file".

- Fixes #

If you modified files in the `./charts/jenkins/` directory, please also include the following:

```[tasklist]
### Submitter checklist
- [x] I bumped the "version" key in `./charts/jenkins/Chart.yml`.
- [x] I added a new changelog entry to `./charts/jenkins/CHANGELOG.md`.
- [x] I followed the [technical requirements](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#technical-requirements).
```

### Special notes for your reviewer
This is mostly inspired by https://github.com/jenkinsci/helm-charts/pull/404

### CODE REVIEW

**Review by timja — COMMENTED** [review]
can you add a unit test please?
https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#unit-tests

**Comment by benzch** [comment]
@timja  added 2 unit test, let me know if there any thing else needed.

**Comment by NotMyFault** [comment]
@benzch Thanks a lot, could you rebase your PR, please? Currently, it conflicts with the default branch.

**Comment by benzch** [comment]
@NotMyFault  rebased main, no more conflicts.

**Review by timja — APPROVED** [review]

**Pull request merged**
