### PR TITLE
project all secrets

### LINKED ISSUE #644: adminSecret, additionalSecrets and additionalExistingSecrets does not update automaticlly
### Describe the bug

The items of adminSecret, additionalSecrets and additionalExistingSecrets are mounted with 'subPath' which means the pod will not receive automated Secret updates
refer: https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically

### Version of Helm and Kubernetes

```markdown
- Helm: v3.8.2
- Kubernetes: v1.22.3
```

### Chart version

3.12.2

### What happened?

```bash
1.
2.
3.
...
```

### What you expected to happen?

Mounted Secrets are updated automatically

### How to reproduce it

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by joelee2012**
Signed-off-by: Joe Lee <lj_2005@163.com>

### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #644 

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by timja** [comment]
tests are failing

**Comment by joelee2012** [comment]
> tests are failing

yes, i'm fixing

**Review by torstenwalter — COMMENTED** [review]
Nice idea.

**Comment by spasche** [comment]
Hello,
This changes how secrets are named in Jcasc.
Here's an example, adapted from the README.

```yaml
controller:
  additionalExistingSecrets:
    - name: secret-credentials
      keyName: token
  JCasC:
    configScripts:
      jenkins-casc-configs: |
        credentials:
          system:
            domainCredentials:
            - credentials:
              - string:
                  secret: ${secret-credentials-token}
```

Now, the additionalExistingSecrets is mounted into `/var/run/secrets/additional/token`, thus it has to be referenced using `${token}` instead of `${secret-credentials-token}`.

Generated snippet:
```yaml
      - name: jenkins-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: token
                path: token
              name: secret-credentials
```

I think the `path` should contain the secret name to keep compatibility.

**Comment by spasche** [comment]
PR in #647

**Pull request merged**
