### PR TITLE
Remote configuration url

### LINKED ISSUE #530: CASC_JENKINS_CONFIG - support for remote url
**Is your feature request related to a problem? Please describe.**
The JCasC plugin supports three variations of providing the value to this environment variable. 
- Path to a folder containing a set of config files. For example, /var/jenkins_home/casc_configs.
- A full path to a single file. For example, /var/jenkins_home/casc_configs/jenkins.yaml.
- A URL pointing to a file served on the web. For example, https://acme.org/jenkins.yaml.

The third option is not supported by the helm chart. 
This would help to externalize the whole jenkins-casc.yaml from the values.yaml file and store it in git.

**Describe the solution you'd like**
support the URL option via values as an additional option to jenkins casc configuration. 
```
controller:
  JCasC: https://acme.org/jenkins.yaml

// or

controller:
  JCasC: 
    url: https://acme.org/jenkins.yaml

```

**Describe alternatives you've considered**
N/A. 

**Additional context**

### PR DESCRIPTION
**Pull request by patbos**
### Which issue this PR fixes

The JCasC plugin supports three variations of providing the value to this environment variable.

Path to a folder containing a set of config files. For example, /var/jenkins_home/casc_configs.
A full path to a single file. For example, /var/jenkins_home/casc_configs/jenkins.yaml.
A URL pointing to a file served on the web. For example, https://acme.org/jenkins.yaml.
The third option is not supported by the helm chart.
This would help to externalize the whole jenkins-casc.yaml from the values.yaml file and store it in git.

- fixes #530 

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Review by timja — COMMENTED** [review]
could you add a test for this please?

**Comment by patbos** [comment]
@timja added test. Not sure why a couple of checks failed, but dont look related to my changes.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
> @timja added test. Not sure why a couple of checks failed, but dont look related to my changes.

that service flakes sometimes and returns 502

**Comment by patbos** [comment]
Thanks @timja for quick review and merge!

**Pull request merged**
