### PR TITLE
#31 Add documentation for configuration of the external url and ingress

### LINKED ISSUE #31: document how an ingress can be configured
maybe even more import, which values can be used to configure external URL

jenkins.url template is defined in:

https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L51-L68

That should give you an idea which values you can set to configure it.

This template is then used to configure it via JCasC:
https://github.com/jenkinsci/helm-charts/blob/91a2a39971d62861e3b1bba8832ddb12fbe25249/charts/jenkins/templates/_helpers.tpl#L159-L163

### PR DESCRIPTION
**Pull request by 11000100111000**
# What this PR does / why we need it
This PR adds some documentation for the configuration of ingress and the jenkins url

# Which issue this PR fixes
- fixes #31 

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Review by torstenwalter — APPROVED** [review]
LGTM @11000100111000 Thank you for adding those docs!

**Comment by 11000100111000** [comment]
@torstenwalter While creating the examples i found some oddities and odd differences between between the primary and secondary ingress definitions(e.g. the empty ` path: []` array has the be present for the `ingress`. Should i adjust those in a new PR or are those actually intended

**Comment by torstenwalter** [comment]
They are not intended. PR is very welcome!

**Comment by 11000100111000** [comment]
Alright! Will create one tomorrow!

**Pull request merged**
