### PR TITLE
Verify name is RFC compatible

### PR DESCRIPTION
**Pull request by mosheavni**
### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by timja** [comment]
Could you include a test?

**Comment by mosheavni** [comment]
> Could you include a test?

Let me know where are other tests and I'll write the logic, I have found nothing interesting under `templates/tests/`

**Comment by mosheavni** [comment]
> Could you include a test?

never did it, no idea how to.

**Comment by torstenwalter** [comment]
@mosheavni

You can run the tests with `helm unittest --helm3 -q --file 'unittests/*.yaml' .` prior to that you need to install the helm unittest plugin `helm plugin install https://github.com/quintush/helm-unittest --version 0.2.6`

https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins/unittests contains quite some example of how things can be tested.

**Pull request closed without merging**
