### PR TITLE
Add Support for Azure Blob Storage Backup

### PR DESCRIPTION
**Pull request by oolfloo**
# What this PR does / why we need it

It enables the backup cron job to use azure blob storage, according to https://github.com/maorfr/skbn documentation in the same easy and nice fashion that it's possible to use s3 for backups.

# Checklist
- [X ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed

### CODE REVIEW

**Comment by torstenwalter** [comment]
@oolfloo CI is failing as you need to increment the version of the chart. As you are adding functionality increasing the minor version would be ok.

Could you also add an entry in CHANGELOG.md?

Bonus points if you add a [unit test](https://github.com/quintush/helm-unittest) for this.

**Comment by torstenwalter** [comment]
@maorfr could you have a look at the changes?

**Comment by oolfloo** [comment]
I wasn't quite sure wether I should actually increase the version number, or if this is up to you. 

I bumped the version and added a changelog. 
Had a quick look at the unit tests - is it possible that the backup-cron is not yet unit-tested at all?

**Review by maorfr — APPROVED** [review]

**Comment by maorfr** [comment]
LGTM from me @torstenwalter!

**Comment by torstenwalter** [comment]
@oolfloo if you fix the merge conflicts with main branch then we can merge it.

**Comment by torstenwalter** [comment]
@oolfloo you are right there are no unit test for it. Feel free to add. Those tests have just been added recently.

**Comment by torstenwalter** [comment]
@oolfloo can you merge main into it?

**Comment by oolfloo** [comment]
Updated based on current main.
Bumped version to 3.0.8. Reflected in changelog as well.

Ci-checks seem fine. Should be ok? @torstenwalter

**Review by torstenwalter — APPROVED** [review]

**Pull request merged**
