### PR TITLE
Disable secret mount on initContainer

### PR DESCRIPTION
**Pull request by bmaximuml**
### What this PR does / why we need it

- disables the volume mount of `jenkins-https-keystore` on the initContainer when `disableSecretMount` is set to true. Currently, setting this variable to true will prevent jenkins from starting up as it will attempt to mount a secret on the init container which does not exist (and, if `disableSecretMount` is set to true, is not wanted).
- Corrects the definition of an environment variable. This was mistakenly defined with keys of `name` and `jenkinsTunnel` rather than `name` and `value` due to an incorrectly handled merge

### Which issue this PR fixes

- This corrects bugs from #814 

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by bmaximuml** [comment]
@timja any thoughts on this?

**Comment by bmaximuml** [comment]
@justusbunsi would you be able to look at this? Thanks

**Comment by justusbunsi** [comment]
> @justusbunsi would you be able to look at this? Thanks

I mean I surely can have a look at it. But why me in particular? As far as I know I am no member of the required and already requested reviewers team. Therefore, my review wouldn't be official.

**Comment by bmaximuml** [comment]
> I mean I surely can have a look at it. But why me in particular? As far as I know I am no member of the required and already requested reviewers team. Therefore, my review wouldn't be official.

My mistake, you left a comment on a previous PR of mine and I assumed you were part of the team.
Feel free to look regardless but I'm mainly interested in the official approval 😉

**Review by timja — APPROVED** [review]

**Comment by bmaximuml** [comment]
Thanks @timja!

**Pull request merged**
