### PR TITLE
Bump Helm (3.4.0 -> 3.8.2) and helm-unittest (0.2.6 -> 0.2.8)

### PR DESCRIPTION
**Pull request by dominykas**
### Which issue this PR fixes

- Updates tests for latest helm. Is this a breaking change?

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] CHANGELOG.md was updated

### CODE REVIEW

**Comment by dominykas** [comment]
Gah, this is now failing with a version bump... but there's no code changes? Shall I still bump patch? Or is this to be considered a breaking change, as the Helm requirement is effectively bumped?

**Comment by timja** [comment]
> Gah, this is now failing with a version bump... but there's no code changes? Shall I still bump patch? Or is this to be considered a breaking change, as the Helm requirement is effectively bumped?

just bump a patch version

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
DCO failing

**Comment by dominykas** [comment]
> DCO failing

OFC it was... 😠

**Review by timja — APPROVED** [review]

**Pull request merged**
