### PR TITLE
Add option to overwrite configuration that it's not present in code

### PR DESCRIPTION
**Pull request by matandomuertos**
### What does this PR do?

The JCasC plugin currently lacks a mechanism for cleaning up manually added configurations through the web UI or remnants of configurations left behind by obsolete plugins, even after their deletion. This situation can potentially hinder the initialization of Jenkins.

This pull request introduces a solution by allowing users to enforce the overwrite of Jenkins configuration with each startup. It achieves this by deleting the config.xml file, compelling JCasC to recreate it.

### Fixes
Inconsistent configuration between Jenkins and JCasC.

### Checklist
- [x] I bumped the "version" key in `./charts/jenkins/Chart.yaml`.
- [x] I added a new changelog entry to `./charts/jenkins/CHANGELOG.md`.
- [x] I followed the [technical requirements](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#technical-requirements).

### CODE REVIEW

**Review by timja — COMMENTED** [review]
This will only overwrite limited configuration from behaviour provided by Jenkins core.
Each plugin will generally have it's own config file.

You would need to delete all xml files in the root of Jenkins home I think

**Comment by matandomuertos** [comment]
> This will only overwrite limited configuration from behaviour provided by Jenkins core. Each plugin will generally have it's own config file.
> 
> You would need to delete all xml files in the root of Jenkins home I think

You are right. So, today I was testing this:
```
rm -rf {{ .Values.controller.jenkinsHome }}/config.xml
rm -rf {{ .Values.controller.jenkinsHome }}/*plugins*.xml
```
and it seems it fixes the issue with all the plugins I tried it. Anyway, I will run a few more test to be sure it works as expected and it doesn't break any other functionality.

**Comment by timja** [comment]
most plugins will include `plugins` in their java package path which is used in the ID but there's no guarantee that all will, and some will have migrated from an older model where it's just the class name without the package and they may have kept it for compatibility.

I'm not sure if there's other XML files in the home directory that you wouldn't want to delete.

**Comment by matandomuertos** [comment]
And... you are right again. I found out today that there are two plugins which their configuration file don't follow the new naming model, `github-plugin-configuration.xml` and `jenkins.model.GlobalBuildDiscarderConfiguration.xml` so I would assume that there are others too. This makes things a little harder because delete all the XML files is not an option. In Jenkins' home directory there are also `credentials.xml` and `scriptApproval.xml` that, in my case, they could be deleted because I have everything in code, but might not be the case of everybody. And also I see some other files that I'm not 100% sure what they are doing.
I will try to find some pattern but I don't see much future on this, unfortunately. If I don't find anything by middle next week I will just close the PR 😞 

Thanks for answering 😄

**Review by timja — APPROVED** [review]
I think ok although it is a bit of a dangerous option, @torstenwalter you ok with this too?

**Comment by matandomuertos** [comment]
Ok, so:
```
rm -f /var/jenkins_home/config.xml
rm -f /var/jenkins_home/*plugins*.xml
find /var/jenkins_home -maxdepth 1 -type f -iname '*configuration*.xml' -exec rm -f {} \;
```
should do the trick. I was testing it with different plugins and it worked for all of them (it doesn't mean that will cover 100% of the plugins because, clearly, I didn't test all of them)

I also added in my customized helm chart something like:
```
{{- range $files =: .Values.controller.JCasC.overwriteCustomConfigFiles }}
    echo "deleting all custom config files"
    rm -f {{ .Values.controller.jenkinsHome }}/{{ $files }}
{{- end }}
```
in case I find some plugin following any other pattern but I don't think it's a good practice for a public helm chart. It might allow people to delete files that are not intended to be deleted. If you think it could work, I could add it anyway.

Thanks!

**Comment by timja** [comment]
lets start with this, it can be extended if required

**Review by timja — APPROVED** [review]

**Comment by jonesbusy** [comment]
Hi,

Thanks for the option. Very useful because never took the time to implement a custom init container

I founds on my controller some files that I want to delete and not matching the pattern and where configuration is defined via JCasC

```
org.jfrog.hudson.ArtifactoryBuilder.xml
locale.xml
cloudbees-disk-usage-simple.xml
org.codefirst.SimpleThemeDecorator.xml
org.jenkinsci.main.modules.sshd.SSHD.xml
hudson.tasks.Mailer.xml
```

Also for some tooling

```
hudson.tasks.Maven.xml
hudson.model.JDK.xml
```

And node monitor that are now supported via JCasC since core 2.440.1

```
nodeMonitors.xml
```

**Pull request merged**
