### PR TITLE
Updated UI tests to use official BATS image

### PR DESCRIPTION
**Pull request by fbuchmeier-abi**
# What this PR does / why we need it

The referenced image `dduportal/bats:0.4.0` has been updated 4 years ago and is still using [docker image manifest v1](https://github.com/moby/moby/blob/master/image/spec/v1.md) which has [been deprecated](https://docs.docker.com/registry/spec/deprecated-schema-v1/).

Current versions [1.1.0](https://github.com/dduportal-dockerfiles/bats/releases/tag/1.1.0) do not have any shell installed and thus can not be used to copy `bats` into the test image.

This is why I have updated the image from `dduportal/bats:0.4.0` to the official `bats/bats:1.2.1` image from [https://hub.docker.com/r/bats/bats](https://hub.docker.com/r/bats/bats).

More information on the v1 deprecation which affected us after implementing our own Docker image cache:

* https://github.com/docker/distribution/releases/tag/v2.7.0
* https://github.com/docker/distribution/issues/2827

# Test Output

```
» helm test jenkins
NAME: jenkins
LAST DEPLOYED: Tue Nov 24 13:38:48 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     jenkins-ui-test-d7lgz
Last Started:   Tue Nov 24 14:08:55 2020
Last Completed: Tue Nov 24 14:08:58 2020
Phase:          Succeeded
NOTES:
[...]
NOTE: Consider using a custom image with pre-installed plugins
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
» kubectl get pods
NAME                       READY   STATUS      RESTARTS   AGE   IP            NODE                               NOMINATED NODE   READINESS GATES
jenkins-84555f5675-fm45l   2/2     Running     0          30m   10.244.0.8    jenkins-helm-chart-control-plane   <none>           <none>
jenkins-ui-test-d7lgz      0/1     Completed   0          7s    10.244.0.14   jenkins-helm-chart-control-plane   <none>           <none>
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
» kubectl logs jenkins-ui-test-d7lgz 
1..1
ok 1 Testing Jenkins UI is accessible
```

# Special notes for your reviewer

Since I can not know which release this change gets pulled into, I did not update the Changelog.md or the Chart.yaml. Hope this is OK.

# Checklist
- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x]  CHANGELOG.md was updated

### CODE REVIEW

**Comment by torstenwalter** [comment]
@fbuchmeier-abi Thats a nice one! Could you rebase your changes on https://github.com/jenkinsci/helm-charts/tree/prepare-3-0-0. Then we could make it part of the 3.0.0 release.

**Comment by fbuchmeier-abi** [comment]
@torstenwalter 

sure, I'm on it (`git rebase prepare-3-0-0 main`). I will update the PR shortly. I suspect you will update the CHANGELOG.md accordingly if required?

Thanks and regards,
Florian.

**Comment by torstenwalter** [comment]
Would be great if you could update the CHANGELOG as part of the PR. There is already a section for 3.0.0.

**Comment by fbuchmeier-abi** [comment]
Awesome, thanks for your patience. If I remember correctly as stated in the PR template, you will squash the commits when integrating them? (the history is not too pretty at the moment).

**Review by timja — APPROVED** [review]

**Comment by torstenwalter** [comment]
@fbuchmeier-abi Thank you! Just mentioned it in #153

**Pull request merged**
