### PR TITLE
Correct docs on disabling plugin installation

### PR DESCRIPTION
**Pull request by donhui**
Related PR: #362

Signed-off-by: donhui <977675308@qq.com>

# What this PR does / why we need it

# Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Review by timja — APPROVED** [review]
ha missed this place in the previous PR in 3.3.14

**Comment by donhui** [comment]
@timja The ci is failed, Is there any way to trigger ci again?

**Comment by timja** [comment]
triggered

**Comment by donhui** [comment]
@timja Unluckily, the ci still fails, Could you trigger it once more, thanks.

**Pull request merged**
