### PR TITLE
Enable setting maxRequestsPerHostStr

### PR DESCRIPTION
**Pull request by GuyCarmy**
Signed-off-by: guycarmy <guycarmy@gmail.com>

# What this PR does / why we need it
This PR allows changing the maxRequestsPerHostStr in order to deal with higher load of agents running non-JNLP containers.
more info [here](https://support.cloudbees.com/hc/en-us/articles/360054642231-Considerations-for-Kubernetes-Clients-Connections-when-using-Kubernetes-Plugin)

# Which issue this PR fixes

I wouldnt say it "fixes" but its relevant in the situation of [JENKINS-56939](https://issues.jenkins.io/browse/JENKINS-56939) (which is already considered resolved but still happened to me until increasing this setting).

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by GuyCarmy** [comment]
I see I had bad timing with 3.1.0 release.
I will rebase and update the PR later to be 3.1.1

**Comment by GuyCarmy** [comment]
Hi @torstenwalter @timja, I will appreciate a review

**Review by torstenwalter — APPROVED** [review]

**Comment by torstenwalter** [comment]
@GuyCarmy I was just on it. Triggered ci to see check if everything is working. There was an issue with GitHub before. Thanks for this improvement!

**Comment by GuyCarmy** [comment]
@torstenwalter amazing, thanks.
yes, I saw that timja's profile returned 504. also the last release (3.1.1) failed...

**Pull request merged**
