### PR TITLE
Improving DRY principle support on Jenkins Controller Ingress host name

### PR DESCRIPTION
**Pull request by Ceddaerrix**
### What does this PR do?

Improving DRY principle support on Jenkins Controller Ingress host name

- Fixes #

### Submitter checklist
- [ ] Introducing TPL function on variables related to hostname in `./charts/jenkins/templates/jenkins-controller-ingress.yaml`

### Special notes for your reviewer

The change is intending to support the following syntax in a _values.yaml_ such as:
```
global:
  jenkinsHostname: "jenkins.my-org.com"

controller:
  ingress:
    enabled: true
    hostName: "{{ .Values.global.jenkinsHostname }}"
    resourceRootUrl: "{{ .Values.global.jenkinsHostname }}"
    tls:
      - hosts:
        - "{{ .Values.global.jenkinsHostname }}"
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
can you take a look at the build failure please?

**Comment by Ceddaerrix** [comment]
> can you take a look at the build failure please?

Failure fixed: it was missing a chart version increment

**Review by timja — COMMENTED** [review]
changelog too

**Comment by Ceddaerrix** [comment]
> changelog too

Done with version increment to 4.6.4

**Review by timja — APPROVED** [review]

**Pull request merged**
