### PR TITLE
Sign releases

### PR DESCRIPTION
**Pull request by NotMyFault**
I would like to sign releases with our key. The workflow setup is sourced from the chart-releaser action.

TODO:
- [ ] Coordinate adding key with the infra team.

### CODE REVIEW

**Review by timja — COMMENTED** [review]
> I would like to sign releases with our key.

Why? Is this common in helm?

I expected to be able to do this keylessly with oidc but apparently it's not implemented 

`https://github.com/helm/helm/issues/11496`

**Comment by NotMyFault** [comment]
> Why? Is this common in helm?

Uh, I can't tell how common it is, but verifying typically happens out of the box, via `helm verify`, using the `verify` part of the helm_release provider in terraform, etc. 
Maybe some people want to verify the integrity before installing our charts?

**Comment by timja** [comment]
> > Why? Is this common in helm?
> 
> Uh, I can't tell how common it is, but verifying typically happens out of the box, via `helm verify`, using the `verify` part of the helm_release provider in terraform, etc. Maybe some people want to verify the integrity before installing our charts?

No ones asked for it as far as I know 🤷. Signing normally adds complexity that isn't much needed if you're delivering the artifacts over https.

Not saying don't do it but unsure if there's much of a benefit.

**Comment by NotMyFault** [comment]
I'll close the PR for now but keep my branch around, just in case 🤷

**Pull request closed without merging**
