### PR TITLE
Adding controller.updateStrategy (#191)

### LINKED ISSUE #191: Allow to set updateStrategy
The chart does not allow to change the statefulset updateStrategy. It is RollingUpdate per default but I would like to set it to OnDelete (to avoid restarting each time the config map is updated because some jobs can be running).

Would it be possible to have such a setting in values ?

### PR DESCRIPTION
**Pull request by olivierboudet**
# What this PR does / why we need it

Add an option controller.updateStrategy to set the spec.updateStrategy for StatefulSet.

# Which issue this PR fixes

- fixes #191

# Special notes for your reviewer

# Checklist
- [ x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped
- [ x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by olivierboudet** [comment]
Is it possible to review this PR before I fix conflicts ?

**Comment by abdennour** [comment]
Guys ! please let's merge this one.
Our usecase is to disable auto rolling update of jenkins controller statefulset. Instead, we want to make it manually using "scale replica 0", then "scale replica 1"
Our old in-house helm chart considered that: 

```yaml
  updateStrategy:
    type: {{ .Values.master.updateStrategy }}
```

As now, we adopted this chart is the official chart, please review this PR

**Review by timja — APPROVED** [review]
looks fine, please resolve conflicts...

**Comment by olivierboudet** [comment]
> looks fine, please resolve conflicts...

Thanks, conflicts are resolved.

**Review by timja — APPROVED** [review]

**Comment by abdennour** [comment]
Thank you guy for your swift response! appreciated!

**Pull request merged**
