### PR TITLE
Bump kiwigrid/k8s-sidecar from 1.15.0 to 1.23.1

### PR DESCRIPTION
**Pull request by NotMyFault**

### CODE REVIEW

**Comment by torstenwalter** [comment]
Looks like the [super-linter update](https://github.com/jenkinsci/helm-charts/pull/841) caused more issues to be reported. Would make sense to fix those in this PR to lower the barrier for other contributions.

**Comment by torstenwalter** [comment]
You have the same issue when updating helm-unittest plugin as the unit tests are only executed when something in a chart is changed.

**Comment by torstenwalter** [comment]
So I always tried to to run those test manually when updating the unittest plugin or ran super-linter on all files locally. See https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md#run-the-container-locally

**Comment by NotMyFault** [comment]
> So I always tried to to run those test manually when updating the unittest plugin or ran super-linter on all files locally. See https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md#run-the-container-locally

I see, makes sense.

**Review by torstenwalter — APPROVED** [review]

**Pull request merged**
