### PR TITLE
Bumping Kubernetes Plugin Version

### LINKED ISSUE #531: Kubernetes Plugin version is set to a broken release.
The current values.yml, specifies a kubernetes plugin which is broken for certain pipelines.

https://issues.jenkins.io/browse/JENKINS-67483
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L238

### PR DESCRIPTION
**Pull request by jseiser**
Signed-off-by: Justin Seiser <justin@sphinxdefense.com>

### What this PR does / why we need it

Bumps Kubernetes Plugin to the bug fixed version.

### Which issue this PR fixes

- fixes #531 

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by torstenwalter** [comment]
Thank you for the PR. You also need to adjust the unit tests for this. I approved the CI pipeline so that you see where it fails.

**Comment by jseiser** [comment]
@torstenwalter 

I guess im missing what needs changed to make it pass.

**Comment by jseiser** [comment]
Any Help on how to make this pass would be great. Thanks.

**Comment by torstenwalter** [comment]
Can you sign your last commit and resolve merge conflicts with `main` branch?

If it's ok for you then I will try to fix the unit tests afterwards.

**Comment by torstenwalter** [comment]
I updated the plugin now as part of #538. You can have a look there what needs to be done for the unit tests. I also added documentation in the CONTRIBUTING.MD how unit tests can be executed. Hope that helps in the future.

**Pull request closed without merging**
