### PR TITLE
Bump configuration-as-code plugin to 1414.v878271fc496f

### LINKED ISSUE #604: Jenkins not starting due to Multiple plugin prerequisites not met
### Describe the bug

Jenkins is not starting it throws the below error.

```
Multiple plugin prerequisites not met:
Plugin kubernetes:1.31.3 (via credentials:1087.v16065d268466) depends on configuration-as-code:1414.v878271fc496f, but there is an older version defined on the top level - configuration-as-code:1.55.1,
Plugin workflow-aggregator:2.6 (via credentials:1087.v16065d268466) depends on configuration-as-code:1414.v878271fc496f, but there is an older version defined on the top level - configuration-as-code:1.55.1,
Plugin git:4.10.2 (via credentials:1087.v16065d268466) depends on configuration-as-code:1414.v878271fc496f, but there is an older version defined on the top level - configuration-as-code:1.55.1
```

### Version of Helm and Kubernetes

```markdown
- Helm: v3.8.1
- Kubernetes: v1.23.5
- Minikube: v1.25.2
```

### Chart version

jenlins-3.11.8

### What happened?

```bash
1. Install jenkins using helm chart, no changes 
2. Jenkins dint start it thrown the error
```

### What you expected to happen?

_No response_

### How to reproduce it

```markdown
helm install jenkins jenkins/jenkins
```

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by rmkanda**
### What this PR does / why we need it
Bump configuration-as-code plugin to 1414.v878271fc496f
### Which issue this PR fixes
- fixes #604 

### Checklist
- [x ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped
- [ x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by rmkanda** [comment]
@timja Could you please review this PR?

**Review by timja — APPROVED** [review]

**Comment by amit-k-yadav** [comment]
@timja this is a rip-off my my PR here -> https://github.com/jenkinsci/helm-charts/pull/597

I opened that 9 days ago and this guy copied the exact same things and changed the checksum, that's all.
My PR got closed without merging because of this.

Request you to look into this.

@rmkanda not cool!!!!! 👎🏼

**Comment by amit-k-yadav** [comment]
@rmkanda I am not getting paid either. It's about open source contributions.
And I didn't respond for a long time? I fixed the issue within 36 hours after the comment from _jseiser_.

If you were facing the issue, then to **_really_** expedite the change you could've tagged _timja_ there instead of copying someone else's work and taking credit for it.
That wasn't ethical man.

**Comment by timja** [comment]
@amit-k-yadav it was a simple PR to update the version in a few places.

I will merge whichever PR is green first for this sort of thing.

Thanks both for your contributions here, much appreciated.

**Pull request merged**
