### PR TITLE
Agent direct connection

### PR DESCRIPTION
**Pull request by bmaximuml**
### What this PR does / why we need it

This enables directConnection for agents to allow agents to be configured to connect direct to the JNLP port on the
controller, preventing the need for an external HTTP endpoint.

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Review by timja — COMMENTED** [review]
can you add a unit test please?

**Review by timja — APPROVED** [review]

**Comment by bmaximuml** [comment]
Thanks @timja !

**Comment by justusbunsi** [comment]
The new setting seems to be missing in `values.yaml`.

**Comment by timja** [comment]
and the README, @bmaximuml possible to do a follow up PR?

**Comment by bmaximuml** [comment]
My apologies, will do

**Pull request merged**
