### PR TITLE
Add support to override default Kubernetes ServerUrl

### PR DESCRIPTION
**Pull request by thekalpesh7**
# What this PR does / why we need it

Previously, there was no value exposed to set the Kubernetes serverUrl and instead it was Hardcoded in the `_helpers.tpl` file. This PR will add the support the override the default Kubernetes serverUrl.

There was some issue in the kubernetes plugin which requires the the Kubernetes plugin to be in the format `<protocol>://<kubernetes_url>:<port>`. If we want to change the url in this format then there was no ability to do this change. Please refer [this post](https://support.cloudbees.com/hc/en-us/articles/360036006032-Kubernetes-Plugin-KubernetesClientException-provisioning-error) for more info.

# Which issue this PR fixes

- N/A

# Special notes for your reviewer

- N/A

# Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by torstenwalter** [comment]
The issue has been solved in the meantime. If you upgrade kubernetes plugin then everything is fine.

**Comment by thekalpesh7** [comment]
@torstenwalter Agree. However, sometimes it is not feasible to update the plugin directly ((e.g. latest version is not supported by Jenkins, etc.) and in that case, there is no other choice but to update the URL itself.  I hope this makes sense!

**Comment by torstenwalter** [comment]
In general I agree, but not for this specific case as the uodated Kubernetes plugin is out for a while and works with latest lts version. In the meantime there was also a security advisory published for oder versions of the plugin so it should not only be ok to update, but also recommended.

I am not sure if we should add a configuration option for something which is already fixed. I mean the chart has so many config options that I would rather avoid adding additional ones if they are not required.

**Comment by thekalpesh7** [comment]
Although it looks specific for this particular issue in the future there could be a new issue similar to this one which requires the serverUrl to be updated E.g. Change in Kubernetes APIs, a new issue in the plugin itself. And it is not always possible to immediately update the Plugin version! In that case, if this option is there then one can go and update the serverUrl directly.

P.S. I am currently using the Latest Jenkins LTS version (2.249.3) but the Latest version of the Kubernetes Plugin (1.28.3) is not supported by the latest Jenkins LTS version. I have updated the plugin to 1.27.7 but still I the issue with Pod template provisioning persists. I have no other option at the moment but go and update the Kubernetes serverUrl through the Jenkins UI :(

**Pull request closed without merging**
