### PR TITLE
Fix issue 592 by adding a regexMatch condition

### LINKED ISSUE #592: Possibility of semver mismatch
Hi.

What about custom name of controller tag?

https://github.com/jenkinsci/helm-charts/blob/43ed7d4785011fa40461805566ef48db222f2bc8/charts/jenkins/templates/_helpers.tpl#L118

I think that helm linter will fails when we set custom controller name e.g. "jenkins-2137" (pulling image from own docker hub)

Helm chart version >= 3.11.7

### PR DESCRIPTION
**Pull request by stijnbrouwers**
Signed-off-by: Stijn Brouwers <stijn@bdcommit.com>

### What this PR does / why we need it
Fixes issue 592 by first applying a regex match to the official semver regex (https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) with a small modification: The patch part of the regex had to be made optional for this to work.

### Which issue this PR fixes
- fixes #592

### Checklist
- [ X ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ X ] Chart Version bumped
- [ X ] CHANGELOG.md was updated

### CODE REVIEW

**Review by timja — COMMENTED** [review]
what about just removing `remotingSecurity: enabled: true` completely?

People on an older version can re-add it themselves if they want to keep it but we should remove it from the defaults?

----

This regex is quite complicated and will still fail if people don't include the version

**Comment by stijnbrouwers** [comment]
For me that sounds good.
I wasn't sure if I could just delete it since I don't really know the impact of it...
I just saw this issue: #616
If this get's introduced and defaulted to false, it will also solve the issue.

**Comment by timja** [comment]
> I just saw this issue: https://github.com/jenkinsci/helm-charts/issues/616

Ah I hadn't seen that, yes that would work and it should be defaulted to not including this

**Comment by stijnbrouwers** [comment]
OK, that's better. Shall I just close this PR without merging then?

**Pull request closed without merging**
