### PR TITLE
Add images metadata for artifacthub

### PR DESCRIPTION
**Pull request by timja**
Was mentioned on IRC:

<halkeye[m]> dev.g4v:halkeye 
timja: btw, we should claim artifacthub repo ownership, and adding the artifacthub annotations - https://artifacthub.io/packages/helm/halkeye/wallabag  - changelog and docker image security scans
11:38 PM 
(i'll do it eventually, just super distracted right now)

### CODE REVIEW

**Comment by torstenwalter** [comment]
@timja that chart is not in this repo. Otherwise we could easily claim ownership. Where is the git repo for it?

**Comment by torstenwalter** [comment]
Just noticed that it is totally unrelated to Jenkins.

**Comment by timja** [comment]
He was just using that as an example of how to configure it,

FYI requested official status in https://github.com/artifacthub/hub/issues/1191

**Comment by timja** [comment]
@torstenwalter you fine with this?

**Comment by timja** [comment]
(changelog is more complicated)

**Review by torstenwalter — APPROVED** [review]

**Comment by torstenwalter** [comment]
Sure! Great to have this!

**Pull request merged**
