### PR TITLE
#75 Add support for enabling websockets via values

### LINKED ISSUE #75: add support for agents connecting via websockets
**Is your feature request related to a problem? Please describe.**
Issue #64 raised awareness that we do not support websockts in the default JCasC configuration.
If people want to use it at the moment they have to disable defaults configuration and do all the other configuration it provides by themselves.

@galindro mentioned in https://github.com/jenkinsci/helm-charts/issues/64#issuecomment-698359540_ that we would need to do the following things:

> The differences are:
> 
> `jenkinsTunnel` should be removed or empty if `webSocket = ​true`
> `jenkinsUrl` should be `http://jenkins.jenkins.svc.cluster.local:8080` if run on k8s
> 
> and the following field should be added:
> `webSocket: true`

This would also solve #70 so that it simplifies connecting external agents to Jenkins, which is running on Kubernetes.

**Describe the solution you'd like**

Would be nice if we would have a flag in the values file via which we could enable websocket support e.g. `agent.websocket: true`, which would do the necessary configuration.

### PR DESCRIPTION
**Pull request by 11000100111000**
# What this PR does / why we need it

Allows configuration to use websockets in the default CasC configuration

# Which issue this PR fixes

- fixes #75 

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by torstenwalter** [comment]
https://github.com/jenkinsci/helm-charts/pull/79/checks?check_run_id=1209739988 show you what to do to fix the DCO check.

**Comment by 11000100111000** [comment]
> https://github.com/jenkinsci/helm-charts/pull/79/checks?check_run_id=1209739988 show you what to do to fix the DCO check.

I'll signoff the commits when i figured out how to fix the problem with agents not being able to connect when using websockets.
Or is that needed for the draft too? 

Do you have any idea what the issue could be?

**Comment by torstenwalter** [comment]
@galindro I got the impression that you figured out how to make it work. Could you help @11000100111000 here?

**Comment by 11000100111000** [comment]
The issue seems to be with the agent since connecting manually using the same command-line the agent dockerfile script produces doesn't work(without the "-webSocket" option it works tho)

**Comment by 11000100111000** [comment]
... you need a trailing slash for the url

**Review by torstenwalter — APPROVED** [review]

**Comment by torstenwalter** [comment]
@11000100111000 Thank you for digging into this. That a great step forward for this helm chart! :clap: :100:

**Pull request merged**
