### PR TITLE
Fix documentation for the kubernetes probes

### PR DESCRIPTION
**Pull request by dduportal**
# What this PR does / why we need it

- The current documentation is not describing the correct values for the Kubernetes probes (wrong keys, missing keys, and false default values)
- If a user is running on a Kubernetes cluster <= 1.18, then startup probes might not be available and the initialDelay should be documented to holds off the liveness probe, to avoid a premature restart of Jenkins triggered by the local Kubelet.

# Which issue this PR fixes

N.A.

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

### CODE REVIEW

**Comment by timja** [comment]
version bump required...

**Review by olblak — DISMISSED** [review]

**Comment by olblak** [comment]
Once chart version is bump

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
if it passes it will merge automatically...

**Comment by dduportal** [comment]
Version bumped (and changelog updated). I thought that a "documentation-only" changed would not have required it, my bad. Should be ok.

**Review by timja — APPROVED** [review]

**Pull request merged**
