### PR TITLE
Disallow ingress on port 50000 when agent listener is disabled

### LINKED ISSUE #463: Network policy should deny ingress on `agentListenerPort` when `agentListenerEnabled` is `false`
**Describe the bug**

When `networkPolicy.enabled` is set to `true`, a `NetworkPolicy` allowing ingress on ports `8080` and `50000` (by default) is created.

However, port `50000` should not be used when `controller.agentListenerEnabled` is `false` (i.e. when only the websocket approach is enabled)

**Version of Helm and Kubernetes**:

Helm Version: not pertinent
Kubernetes Version: not pertinent

**Which version of the chart**:

Latest (3.5.18)

---

I'll PR a fix shortly, unless someone objects or gets there first.

### PR DESCRIPTION
**Pull request by dominykas**
Closes https://github.com/jenkinsci/helm-charts/issues/463

Signed-off-by: Dominykas Blyžė <hello@dominykas.com>

### Which issue this PR fixes

- fixes #463 

### Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] CHANGELOG.md was updated

---

I wasn't sure about updating Chart Version / CHANGELOG - there's an outstanding PR, which already includes the next patch version? Happy to make whatever changes are necessary!

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by dominykas** [comment]
Updated this with `main` - is there anything else I can do here (and in the other PR I have) to help move this forward?

**Comment by timja** [comment]
> Updated this with `main` - is there anything else I can do here (and in the other PR I have) to help move this forward?

it was just that, it was conflicted

**Comment by timja** [comment]
o and changelog entry is missing

**Review by timja — APPROVED** [review]

**Comment by dominykas** [comment]
Updated with the assumption that this will be the next thing to get merged in terms of versioning...

**Comment by timja** [comment]
> Updated with the assumption that this will be the next thing to get merged in terms of versioning...

yup, it's always a race, but if the build passed you're up next

**Comment by dominykas** [comment]
Thanks 🙇

**Pull request merged**
